export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const BURGER_PURCHASED = "BURGER_PURCHASED";
export const BURGER_PURCHASE_FAILED = "BURGER_PURCHASE_FAILED";
export const BURGER_PURCHASE_STARTED = "BURGER_PURCHASE_STARTED";
export const BURGER_PURCHASE_COMPLETED = "BURGER_PURCHASE_COMPLETED";
